version: '4'
services:
  mysql:
    image: mysql:latest 
    container_name: inventory-mysql 
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - D:/shopping site/inventory-service/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      